### ISSUE TITLE
AKWF for Surge

### ISSUE THREAD

**Issue by mortfell** [KristofferKarlAxelEkstrand/AKWF-FREE#1]
Hey there!
I made some versions of the AKWF single cycle waveforms for the FOSS synth [Surge](https://surge-synthesizer.github.io)!
I have them ready to upload here if you'd like.

Surge likes power-of-2 table sizes so:
I converted the waveforms to 64 sample, 512 sample and 1024 sample versions

I also have a readme with some instructions and info ready to go.

thanks!

**Comment by KristofferKarlAxelEkstrand** [comment]
COOL! I would love to add it to this project or just add it somewhere. Are you able to push it into this and I just ok it (I dont remember how I set it up)

**Comment by mortfell** [comment]
Awesome :)
Hmmm I'm not sure, I'm not suuuper familiar with Github. I can't push to the master though.

I think the easiest thing would be to make a new branch for collaborators and give me access to that, and then you can push the code to master once I've uploaded!

**Comment by mortfell** [comment]
Or I can just send you the files some other way

**Comment by mortfell** [comment]
Hey Kristoffer!
So here is Surge's "Additional Downloads" folder, which includes the stuff I was talking about:
https://github.com/surge-synthesizer/surge-synthesizer.github.io/tree/master/assets/wiki/Additional%20Content

These ones are different sizes of the single cycles:
AKWF-1024.zip
AKWF-512.zip
AKWF-64.zip

These ones are wavetables created from the single cycles:
AKWF-WAV-2048 (these are Serum wavetables)
AKWF-WT-512

So yeah the files are up here if anyone wants them!
If you want to include those here in this repository, I also made this README file which explains a bit about the files:
[README.md.zip](https://github.com/KristofferKarlAxelEkstrand/AKWF-FREE/files/3639023/README.md.zip)

Thanks for the awesome wavetables!

**Comment by jwakely** [comment]
> I think the easiest thing would be to make a new branch for collaborators and give me access to that, and then you can push the contents to master once I've uploaded!

The usual workflow is to fork the repository, add the new files to your own fork, then [create a pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) for Kristoffer to merge the changes from your fork into his.

**Comment by mortfell** [comment]
Ok thanks for letting me know!
I will attempt this

**Comment by mortfell** [comment]
I made a pull request for a new fork with the Surge files. Closing this issue.
